# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import streaming_pb2 as streaming__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in streaming_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StreamingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamBatchedMessages = channel.stream_stream(
                '/streaming.StreamingService/StreamBatchedMessages',
                request_serializer=streaming__pb2.MessageBatch.SerializeToString,
                response_deserializer=streaming__pb2.MessageBatch.FromString,
                _registered_method=True)


class StreamingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamBatchedMessages(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StreamingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamBatchedMessages': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamBatchedMessages,
                    request_deserializer=streaming__pb2.MessageBatch.FromString,
                    response_serializer=streaming__pb2.MessageBatch.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'streaming.StreamingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('streaming.StreamingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StreamingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamBatchedMessages(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/streaming.StreamingService/StreamBatchedMessages',
            streaming__pb2.MessageBatch.SerializeToString,
            streaming__pb2.MessageBatch.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class StreamingAnswersStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamAnswer = channel.stream_stream(
                '/streaming.StreamingAnswers/StreamAnswer',
                request_serializer=streaming__pb2.MessageBatch.SerializeToString,
                response_deserializer=streaming__pb2.MessageBatch.FromString,
                _registered_method=True)


class StreamingAnswersServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamAnswer(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StreamingAnswersServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamAnswer': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamAnswer,
                    request_deserializer=streaming__pb2.MessageBatch.FromString,
                    response_serializer=streaming__pb2.MessageBatch.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'streaming.StreamingAnswers', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('streaming.StreamingAnswers', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StreamingAnswers(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamAnswer(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/streaming.StreamingAnswers/StreamAnswer',
            streaming__pb2.MessageBatch.SerializeToString,
            streaming__pb2.MessageBatch.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
