# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: streaming.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'streaming.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fstreaming.proto\x12\tstreaming\" \n\x0cMessageBatch\x12\x10\n\x08messages\x18\x01 \x03(\t2a\n\x10StreamingService\x12M\n\x15StreamBatchedMessages\x12\x17.streaming.MessageBatch\x1a\x17.streaming.MessageBatch(\x01\x30\x01\x32X\n\x10StreamingAnswers\x12\x44\n\x0cStreamAnswer\x12\x17.streaming.MessageBatch\x1a\x17.streaming.MessageBatch(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'streaming_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGEBATCH']._serialized_start=30
  _globals['_MESSAGEBATCH']._serialized_end=62
  _globals['_STREAMINGSERVICE']._serialized_start=64
  _globals['_STREAMINGSERVICE']._serialized_end=161
  _globals['_STREAMINGANSWERS']._serialized_start=163
  _globals['_STREAMINGANSWERS']._serialized_end=251
# @@protoc_insertion_point(module_scope)
