name: 'publish'
on:
  push:
    branches:
      - release

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-20.04] #[macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libglib2.0-dev pkg-config libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf protobuf-compiler
          npm install @types/jquery --save-dev
      - name: check pkg-config
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          pkg-config --modversion glib-2.0


      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Specify the Python version
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install grpcio
          pip install grpcio_tools
          pip install protobuf

      - name: Install proto
        run: |
          python -m grpc_tools.protoc -I add_to_db --python_out=. --pyi_out=. --grpc_python_out=. protos/streaming.proto
        working-directory: met-id/src-tauri/src
      

      - name: Use Pyinstaller (Windows)
        if: matrix.platform == 'windows-latest'
        run: |
          ./make_executables.ps1
        working-directory: met-id/src-tauri/pyinstaller
        shell: pwsh

      - name: Use Pyinstaller (MacOS)
        if: matrix.platform == 'macos-latest'
        run: |
          chmod +x make_macos_executables.sh
          ./make_macos_executables.sh
        working-directory: met-id/src-tauri/pyinstaller
        shell: bash

      - name: Use Pyinstaller (Linux)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          chmod +x make_linux_executables.sh
          ./make_linux_executables.sh
        working-directory: met-id/src-tauri/pyinstaller
        shell: bash
    

      - name: Import Apple Certificate (MacOS)
        if: matrix.platform == 'macos-latest'
        env:
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
        run: |
          echo "${APPLE_CERTIFICATE}" | base64 --decode > apple_certificate.p12
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import apple_certificate.p12 -k build.keychain -P "${APPLE_CERTIFICATE_PASSWORD}" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain

      - name: Sign MacOS Binaries
        if: matrix.platform == 'macos-latest'
        env:
          APPLE_DEVELOPER_ID: ${{ secrets.APPLE_DEVELOPER_ID }}
        run: |
          find met-id/src-tauri/pyinstaller/dist -type f -exec codesign --deep --force --verify --verbose --sign "${APPLE_DEVELOPER_ID}" --options runtime --timestamp {} \;
      

      - name: Upload Bin
        run: |
          # Add your upload commands here


      - name: Install Frontend Dependencies
        run: npm install # change this to npm or pnpm depending on which one you use
        working-directory: met-id

      - name: Build Frontend
        run: npm run build
        working-directory: met-id


      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        with:
          tagName: Met-ID-v0.1.0 # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'Met-ID v0.1.0'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: false
          prerelease: false
